POST http://localhost:8080/events
content-Type: application/json

{
    "name":"test event2",
    "description":"Test description text...",
    "location":"a test location",
    "dateTime":"2026-07-24T09:05:12.000Z"
}