POST http://localhost:8080/events/1/register
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJleHAiOjE3ODUyNjc0MzAsInVzZXJJZCI6MX0.awXVXRGmeQRMQnzps2C6qjretKVfiDB3tmLhojmtHuc
